### ISSUE TITLE
Advanced problem does not work.

### ISSUE THREAD

**Issue by kwangkim** [UCL-INGI/INGInious#393]
I am trying add an Advanced problem with boxes.

https://inginious.readthedocs.io/en/v0.5/teacher_doc/task_file.html#advanced-code-problem

But it does not seem to work properly.
I copied and pasted a sample code.
```
type: code
header: some text
name: And again, another name
boxes:
    boxId1:
        type: text
        content: Some additional text
    boxId2:
        type: input-text
        maxChars: 10
        optional: true
    boxId3:
        type: multiline
        maxChars: 1000
        lines: 8
        language: java
```
It only works as usual `code` problem, **boxes do not work**.

How can I fix this?
