### ISSUE TITLE
'/task/run' could not be found

### ISSUE THREAD

**Issue by toolcreator** [UCL-INGI/INGInious#799]
Hello,

I'm trying to setup v0.7 in a docker-compose environment, but can't get grading to work.
Shortly after submitting, the error `'/task/run' could not be found` is displayed, even though a run script is provided and in the correct place.
Here's my setup:

*directory structure*
```
.
├── backup
├── configuration.yaml
├── docker-compose.yml
├── Dockerfile
├── entry.sh
└── tasks
    └── cc
        ├── course.yaml
        └── grammar
            ├── run.py
            └── task.yaml
```

*docker-compose.yml*

```yaml
services:
  mongo:
    image: mongo:5
  inginious:
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./configuration.yaml:/home/inginious/configuration.yaml:ro
      - ./tasks:/home/inginious/tasks
      - ./backup:/home/inginious/backup
    ports:
      - 80:8080
```

*Dockerfile*

```dockerfile
FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
  && apt-get install -y \
  git \
  gcc \
  tidy \
  python3 \
  python3-pip \
  python3-dev \
  libzmq3-dev \
  apt-transport-https \
  curl \
  gnupg \
  lsb-release

RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
  | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg \
  && echo \
  "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" \
  | tee /etc/apt/sources.list.d/docker.list > /dev/null \
  && apt-get update \
  && apt-get install -y docker-ce docker-ce-cli

RUN pip3 install git+https://github.com/UCL-INGI/INGInious.git@inginious-0.7#egg=INGInious[ldap]

WORKDIR /home/inginious

RUN mkdir tasks backup

COPY entry.sh .

ENTRYPOINT ["./entry.sh", "--config", "./configuration.yaml", "--host", "0.0.0.0"]
```

*entry.sh*

```bash
#!/usr/bin/env sh

echo yes | inginious-container-update
inginious-webapp "$@"
```

I execute the container update because of the information I read in #704 and #713.

*configuration.yaml*

```yaml
backend: local
log_level: INFO
web_debug: false
local-config:
    concurrency: 4
mongo_opt:
    host: mongo
    database: INGInious
tasks_directory: /home/inginious/tasks
use_minified_js: true
backup_directory: /home/inginious/backup
plugins:
  - plugin_module: inginious.frontend.plugins.auth.ldap_auth
    id: ldap
    host: "redacted"
    encryption: "ssl" #can be tls or none
    base_dn: "redacted"
    request: "(uid={})"
    name: "LDAP Login"
superadmins:
  - admin
maintenance: false
reverse-proxy-config:
    enable: false
    x_for: 1
    x_host: 1
allow_deletion: false
allow_registration: false
session_parameters:
    secret_key: "redacted"
```

If you need any more information I'll happily provide it, I've run out of things to try.
Some things I tried:

- Using `master` instead of `inginious-0.7`
- Cloning this repo and building the rocky-based images instead of running the container update
- Replace run.py with a run.sh or run file with shebang
- Combinations of the above and probably a few thing I don't remember (sorry)

Any help would be appreciated!

**Comment by anthonygego** [comment]
Are you able to run a submission in SSH debug mode and see if the files are missing or not ? Do you see any error message in the webapp logs ? You may also want to set a path for the agent temporary folder, which is used to copy task files before mounting them into the container, to be sure it's writable and accessible to all the components :

     local-config:
        tmp_dir: /a/path/to/a/shared/and/writable/temp/folder

**Comment by toolcreator** [comment]
Thanks for the incredibly quick reply!

I tried the SSH Debug mode, logged into the container with the provided password, and /task was indeed empty.

Afterwards I tried setting the `tmp_dir` to `/tmp` which by default has 777 permissions.
Interestingly, after launching the webapp, the permissions are changed to 755 (I confirmed they were 777 right before by putting an `ls -la /` into *entry.sh*, then ran `docker compose exec inginious ls -la /` to find the changed permissions).

There are no error messages in the logs (I've changed loglevel to DEBUG):

```
inginious-docker-inginious-1  | 2022-03-10 12:05:29,893 - inginious.course_factory - INFO - Caching course cc
inginious-docker-inginious-1  | 2022-03-10 12:05:29,924 - inginious.webapp.submissions - INFO - New submission from admin - redacted - cc/grammar - 172.18.0.1
inginious-docker-inginious-1  | 2022-03-10 12:05:29,925 - inginious.backend - INFO - Adding a new job b'\x00F\xe8|\xcd' b6e89f1f-7375-4dbf-a69f-130f7573bb96 to the queue
inginious-docker-inginious-1  | 2022-03-10 12:05:29,925 - inginious.backend - INFO - Sending job b'\x00F\xe8|\xcd' b6e89f1f-7375-4dbf-a69f-130f7573bb96 to agent b'\x00\xe2UX\xed'
inginious-docker-inginious-1  | 2022-03-10 12:05:29,926 - inginious.agent.docker - INFO - Received request for jobid b6e89f1f-7375-4dbf-a69f-130f7573bb96
inginious-docker-inginious-1  | 2022-03-10 12:05:29,926 - inginious.webapp.requests - INFO - 172.18.0.1:43506 - "- POST /course/cc/grammar" - 200 OK
inginious-docker-inginious-1  | 172.18.0.1 - - [10/Mar/2022 12:05:29] "POST /course/cc/grammar HTTP/1.1" 200 -
inginious-docker-inginious-1  | 2022-03-10 12:05:29,927 - inginious.backend - DEBUG - Job b6e89f1f-7375-4dbf-a69f-130f7573bb96 started on agent b'\x00\xe2UX\xed'
inginious-docker-inginious-1  | 2022-03-10 12:05:29,928 - inginious.client - DEBUG - Job b6e89f1f-7375-4dbf-a69f-130f7573bb96 started
inginious-docker-inginious-1  | 2022-03-10 12:05:30,131 - inginious.agent.docker - DEBUG - Sending 3890 bytes to container
inginious-docker-inginious-1  | 2022-03-10 12:05:30,131 - inginious.agent.docker - DEBUG - 32727000
inginious-docker-inginious-1  | 2022-03-10 12:05:30,260 - inginious.agent.docker - DEBUG - Received msg result from container 013d7eb60df8b3ffac4cfd7000c72f7c0376efdf59dbe78ce48b7f64331d816f
inginious-docker-inginious-1  | 2022-03-10 12:05:30,290 - inginious.agent.docker - DEBUG - Closing 013d7eb60df8b3ffac4cfd7000c72f7c0376efdf59dbe78ce48b7f64331d816f
inginious-docker-inginious-1  | 2022-03-10 12:05:30,297 - inginious.agent.docker - DEBUG - Container output ended with an IncompleteReadError; It was probably killed.
inginious-docker-inginious-1  | 2022-03-10 12:05:30,312 - inginious.backend - INFO - Job b6e89f1f-7375-4dbf-a69f-130f7573bb96 finished on agent b'\x00\xe2UX\xed'
inginious-docker-inginious-1  | 2022-03-10 12:05:30,312 - inginious.client - DEBUG - Job b6e89f1f-7375-4dbf-a69f-130f7573bb96 done
inginious-docker-inginious-1  | 2022-03-10 12:05:30,960 - inginious.webapp.requests - INFO - 172.18.0.1:43512 - "- POST /course/cc/grammar" - 200 OK
inginious-docker-inginious-1  | 172.18.0.1 - - [10/Mar/2022 12:05:30] "POST /course/cc/grammar HTTP/1.1" 200 -
```

I'm no looking through INGInious's code to try and find out why the permissions change, but that's rather tedious as I'm unfamiliar with the code bases.
Any additionally hints and ideas are certainly welcome.

**Comment by toolcreator** [comment]
# Solution

[This stackoverflow post](https://stackoverflow.com/questions/31381322/docker-in-docker-cannot-mount-volume) about mounts when using docker in docker makes clear what the problem is:
Mount paths are seen as paths on the host, so when my INGInious container tried to mount some directory on its filesystem to the container it created, docker silently failed to do that, because the path does not exist on the host machine.

The solution is rather simple: The paths to the temporary directory on the host and in the container must match!
In the following only the relevant parts of the files are shown for brevity (see above for the rest).

*Dockerfile*

```dockerfile
RUN mkdir tasks backup /tmp/inginious
```

*configuration.yaml*

```yaml
local-config:
    tmp_dir: /tmp/inginious
```

*docker-compose.yml*

```yaml
inginious:
    volumes:
      - /tmp/inginious:/tmp/inginious
```

Thanks again @anthonygego for replying so quickly and pushing my search in the right direction!
